# Generated by Django 3.2.9 on 2021-12-15 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appart',
            fields=[
                ('app_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('surface', models.IntegerField(null=True, verbose_name='surface')),
                ('prix', models.IntegerField(null=True, verbose_name='price')),
                ('nb_pièces', models.IntegerField(null=True, verbose_name='nombre de pièces')),
            ],
        ),
        migrations.CreateModel(
            name='Caract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_ski', models.IntegerField(null=True, verbose_name='approche à station ski')),
                ('piscine', models.BooleanField(default=True, verbose_name='disponible')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('programm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=200, verbose_name='Nom du programme')),
                ('statu', models.BooleanField(default=True, verbose_name='disponible')),
                ('appartements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.appart')),
            ],
        ),
        migrations.AddField(
            model_name='appart',
            name='caractéristiques',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.caract'),
        ),
    ]
